const K="quick-copy-pwa-v3",MAX=20;
function T(text="",auto=false){return{id:crypto.randomUUID(),text,auto}}
function blanks(){return Array.from({length:5},()=>T())}
let s=load(),deleteIndex=-1,dragIndex=-1,pointerId=null;
const $=q=>document.querySelector(q),items=$("#items"),toast=$("#toast"),confirm=$("#confirm");
function load(){try{const x=JSON.parse(localStorage.getItem(K));if(Array.isArray(x)&&x.length)return x.map(v=>({id:v.id||crypto.randomUUID(),text:String(v.text||""),auto:!!v.auto}))}catch{}return blanks()}
function save(){localStorage.setItem(K,JSON.stringify(s))}
function esc(x){return x.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function msg(x){toast.textContent=x;toast.hidden=false;clearTimeout(msg.t);msg.t=setTimeout(()=>toast.hidden=true,1800)}
function inc(x){const a=[...x.matchAll(/\d+/g)];if(!a.length)return null;const m=a.at(-1),n=String(Number(m[0])+1).padStart(m[0].length,"0");return x.slice(0,m.index)+n+x.slice(m.index+m[0].length)}
async function cp(x){await navigator.clipboard.writeText(x)}
function render(){items.innerHTML="";s.forEach((o,i)=>{const r=document.createElement("article");r.className="row";r.dataset.i=i;r.innerHTML=`<button class="handle" type="button" aria-label="${i+1}行目を並べ替え">☰</button><span class="num">${i+1}</span><input class="txt" value="${esc(o.text)}" aria-label="${i+1}行目のテキスト"><input class="check" type="checkbox" ${o.auto?"checked":""} aria-label="${i+1}行目の自動採番"><button class="delete-row" type="button" aria-label="${i+1}行目を削除"><svg class="trash-icon" viewBox="0 0 64 64" aria-hidden="true"><rect x="5" y="6" width="54" height="54" rx="12" fill="#f3f3f3"/><path d="M22 14h20c2 0 4 2 4 4v2H18v-2c0-2 2-4 4-4Z" fill="#494949"/><path d="M14 22h36l-3 31c-.4 4-3.1 7-7 7H24c-3.9 0-6.6-3-7-7L14 22Z" fill="#494949"/><path d="M13 20h38v5H13z" fill="#494949"/><path d="M25 31l1.2 19M32 31v19M39 31l-1.2 19" stroke="#fff" stroke-width="4.5" stroke-linecap="round"/></svg></button><button class="copy" type="button">コピー</button>`;
const t=r.querySelector(".txt"),c=r.querySelector(".check");t.oninput=()=>{s[i].text=t.value;save()};c.onchange=()=>{s[i].auto=c.checked;save()};r.querySelector(".delete-row").onclick=()=>{deleteIndex=i;confirm.querySelector("p").textContent=`${i+1}行目を削除しますか？`;confirm.showModal()};r.querySelector(".copy").onclick=async()=>{if(!t.value)return msg("空欄です");try{const old=t.value;await cp(old);if(c.checked){const n=inc(old);if(n!==null){s[i].text=t.value=n;save()}}msg("コピーしました")}catch{msg("コピーできませんでした")}};r.querySelector(".handle").onpointerdown=e=>drag(e,i,r);items.append(r)})}
function move(a,b){if(b<0||b>=s.length)return;const[x]=s.splice(a,1);s.splice(b,0,x);save();render()}
function drag(e,i,r){dragIndex=i;pointerId=e.pointerId;r.classList.add("dragging");e.preventDefault();const mm=v=>{if(v.pointerId!==pointerId)return;document.querySelectorAll(".target").forEach(x=>x.classList.remove("target"));const target=document.elementFromPoint(v.clientX,v.clientY)?.closest(".row");if(target&&target!==r)target.classList.add("target")};const uu=v=>{if(v.pointerId!==pointerId)return;document.removeEventListener("pointermove",mm);document.removeEventListener("pointerup",uu);document.removeEventListener("pointercancel",uu);const tr=document.elementFromPoint(v.clientX,v.clientY)?.closest(".row"),j=tr?Number(tr.dataset.i):i;document.querySelectorAll(".target").forEach(x=>x.classList.remove("target"));j!==i?move(i,j):render()};document.addEventListener("pointermove",mm,{passive:false});document.addEventListener("pointerup",uu);document.addEventListener("pointercancel",uu)}
$("#add").onclick=()=>{if(s.length>=MAX)return msg("最大20行です");s.push(T());save();render();requestAnimationFrame(()=>items.lastElementChild.querySelector(".txt").focus())};
$("#no").onclick=()=>confirm.close();$("#yes").onclick=()=>{confirm.close();s.splice(deleteIndex,1);if(!s.length)s=[T()];save();render();msg("削除しました")};
$("#clear").onclick=()=>{s=s.map(x=>({...x,text:"",auto:false}));save();render();msg("クリアしました")};
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));render();